import { themeColors } from "./theme";

export const cssVariables = {
  light: {
    '--background': themeColors.colors.netral.white,
    '--pagination': themeColors.colors.netral.white,
    '--text': themeColors.colors.netral[800],
    '--text-muted': themeColors.colors.netral[600],
    '--border': themeColors.colors.netral[200],
    '--card-bg': themeColors.colors.netral[100],
    '--shadow': themeColors.colors.netral[300],
    '--radio': themeColors.colors.netral[700],
    '--tabs-label': themeColors.colors.primary[500],
    '--tabs-background': themeColors.colors.secondary[100],
    '--toggle': themeColors.colors.netral.white,
    '--dropdown': themeColors.colors.netral.white,
    '--dot': themeColors.colors.netral.dark,
    
    '--primary': themeColors.colors.primary[500],
    '--primary-pagination': themeColors.colors.primary[500],
    '--primary-table': themeColors.colors.primary[500],
    '--primary-input': themeColors.colors.primary[700],
    '--primary-hover': themeColors.colors.primary[600],
    '--primary-light': themeColors.colors.primary[100],
    '--primary-dark': themeColors.colors.primary[800],
    '--primary-tabs': themeColors.colors.primary[500],
    '--primary-status': themeColors.colors.primary[200],
    '--primary-icon-wrapper': themeColors.colors.primary[100],
    
    '--secondary': themeColors.colors.secondary[500],
    '--secondary-modal': themeColors.colors.secondary[200],
    '--secondary-hover': themeColors.colors.secondary[600],
    '--secondary-list': themeColors.colors.secondary[100],
    '--secondary-light': themeColors.colors.secondary[100],
    '--secondary-tabs': themeColors.colors.secondary[200],
    '--secondary-disabled': themeColors.colors.secondary[300],
    '--secondary-disabled-text': themeColors.colors.netral.white,
    '--secondary-employee': themeColors.colors.secondary[100],

    
    '--success': themeColors.colors.success[500],
    '--success-status': themeColors.colors.success[100],
    '--success-persen': themeColors.colors.success[700],
    '--success-hover': themeColors.colors.success[600],
    '--success-dot': themeColors.colors.success[600],
    '--success-order': themeColors.colors.success[900],
    '--success-light': themeColors.colors.success[100],
    
    '--warning': themeColors.colors.warning[500],
    '--warning-status': themeColors.colors.warning[100],
    '--warning-tag': themeColors.colors.warning[500],
    '--warning-hover': themeColors.colors.warning[600],
    '--warning-light': themeColors.colors.warning[100],
    
    '--danger': themeColors.colors.danger[500],
    '--danger-tag': themeColors.colors.danger[500],
    '--danger-input': themeColors.colors.danger[400],
    '--danger-hover': themeColors.colors.danger[600],
    '--danger-light': themeColors.colors.danger[100],
    
    '--netral-100': themeColors.colors.netral[100],
    '--netral-200': themeColors.colors.netral[200],
    '--netral-300': themeColors.colors.netral[300],
    '--netral-400': themeColors.colors.netral[400],
    '--netral-500': themeColors.colors.netral[500],
    '--netral-600': themeColors.colors.netral[600],
    '--netral-700': themeColors.colors.netral[700],
    '--netral-800': themeColors.colors.netral[800],
  },
  dark: {
    '--background': themeColors.colors.netral.dark,
    '--text': themeColors.colors.netral[100],
    '--text-muted': themeColors.colors.netral[400],
    '--border': themeColors.colors.netral[600],
    '--card-bg': themeColors.colors.netral[700],
    '--shadow': themeColors.colors.netral[800],
    '--radio': themeColors.colors.netral[300],
    '--tabs-label': themeColors.colors.netral.white,
    '--tabs-background': themeColors.colors.netral[700],
    '--toggle': themeColors.colors.netral.white,
    '--dropdown': themeColors.colors.netral[800],
    '--dot': themeColors.colors.netral.white,
    
    '--primary': themeColors.colors.primary[400],
    '--primary-table': themeColors.colors.primary[100],
    '--primary-pagination': themeColors.colors.primary[500],
    '--primary-input': themeColors.colors.primary[500],
    '--primary-hover': themeColors.colors.primary[300],
    '--primary-light': themeColors.colors.primary.dark,
    '--primary-dark': themeColors.colors.primary[600],
    '--primary-tabs': themeColors.colors.netral.white,
    '--primary-status': themeColors.colors.primary[400],
    '--primary-icon-wrapper': themeColors.colors.primary[400],
    
    '--secondary': themeColors.colors.secondary[400],
    '--secondary-modal': themeColors.colors.secondary.dark,
    '--secondary-list': themeColors.colors.primary[400],
    '--secondary-hover': themeColors.colors.secondary[300],
    '--secondary-tabs': themeColors.colors.netral[700],
    '--secondary-disabled': themeColors.colors.primary.dark,
    '--secondary-disabled-text': themeColors.colors.secondary[900],
    '--secondary-employee': themeColors.colors.netral[700],
    '--secondary-light': themeColors.colors.secondary.dark,
    
    '--success': themeColors.colors.success[400],
    '--success-status': themeColors.colors.success[700],
    '--success-persen': themeColors.colors.success[700],
    '--success-hover': themeColors.colors.success[300],
    '--success-dot': themeColors.colors.success[600],
    '--success-order': themeColors.colors.success[500],
    '--success-light': themeColors.colors.success.dark,
    
    '--warning': themeColors.colors.warning[400],
    '--warning-status': themeColors.colors.warning[600],
    '--warning-tag': themeColors.colors.warning[500],
    '--warning-hover': themeColors.colors.warning[300],
    '--warning-light': themeColors.colors.warning.dark,
    
    '--danger': themeColors.colors.danger[400],
    '--danger-tag': themeColors.colors.danger[500],
    '--danger-input': themeColors.colors.danger[500],
    '--danger-hover': themeColors.colors.danger[300],
    '--danger-light': themeColors.colors.danger.dark,
    
    '--netral-100': themeColors.colors.netral[800],
    '--netral-200': themeColors.colors.netral[700],
    '--netral-300': themeColors.colors.netral[600],
    '--netral-400': themeColors.colors.netral[500],
    '--netral-500': themeColors.colors.netral[400],
    '--netral-600': themeColors.colors.netral[300],
    '--netral-700': themeColors.colors.netral[200],
    '--netral-800': themeColors.colors.netral[100],
  }
};