import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { ThemeProvider } from "@/lib/provider/theme-provider/theme-provider";
import QueryProvider from "@/lib/provider/query-provider";
import { TimerProvider } from "@/lib/provider/timer-provider/timer-provider";
import ServiceWorkerRegister from "@/components/ServiceWorkers/ServiceWorkerRegister";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Web Pos Digidreams Spaces",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  other: {
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'default',
    'apple-mobile-web-app-title': 'NextPWA'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <QueryProvider>
            <ThemeProvider>
              <TimerProvider>
              {children}
              <ServiceWorkerRegister/>
              </TimerProvider>
            </ThemeProvider>
          </QueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
